# Generated by Django 2.1.5 on 2019-01-24 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('passenger_count', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(max_length=200)),
                ('can_shared', models.BooleanField()),
                ('is_completed', models.BooleanField()),
                ('arrival_time', models.DateTimeField(verbose_name='date published')),
                ('special_request', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.Ride'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
