# Generated by Django 2.1.5 on 2019-01-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_auto_20190124_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='can_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
