# Generated by Django 2.1.5 on 2019-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_auto_20190128_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(max_length=200),
        ),
    ]
