# Generated by Django 2.1.5 on 2019-01-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_auto_20190128_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='special_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searchfromsharer',
            name='special_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
