# Generated by Django 2.1.5 on 2019-01-30 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_auto_20190130_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='searchFromDriver',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='departure',
            new_name='start_location',
        ),
        migrations.RemoveField(
            model_name='searchfromsharer',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='searchfromsharer',
            name='special_request',
        ),
        migrations.RemoveField(
            model_name='searchfromsharer',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='searchfromsharer',
            name='earliest_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='eraliest_arrival'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchfromsharer',
            name='latest_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='latest_arrival'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
