# Generated by Django 2.1.5 on 2019-01-30 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0008_auto_20190130_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(related_name='assign_sharer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchfromsharer',
            name='earliest_time',
            field=models.DateTimeField(verbose_name='Earliest Arrival Time'),
        ),
        migrations.AlterField(
            model_name='searchfromsharer',
            name='latest_time',
            field=models.DateTimeField(verbose_name='Latest Arrival Time'),
        ),
    ]
