# Generated by Django 2.1.5 on 2019-01-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_auto_20190130_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchfromsharer',
            old_name='earliest_time',
            new_name='earliest_arrival_time',
        ),
        migrations.RenameField(
            model_name='searchfromsharer',
            old_name='latest_time',
            new_name='latest_arrival_time',
        ),
    ]
