# Generated by Django 2.1.5 on 2019-01-31 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0012_auto_20190131_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, related_name='assign_sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
