# Generated by Django 2.1.5 on 2019-02-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0013_auto_20190131_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_real_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ride',
            name='license_plate_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
