# Generated by Django 2.1.5 on 2019-01-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
