# Generated by Django 2.1.5 on 2019-01-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190127_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
